version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    volumes:
      - $HOME/database:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: phonebook_db
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      server:
        aliases:
          - mysqldb

  phone-book-api:
    container_name: phone-book-api
    build:
      context: .
    image: phonebook-api:v1.1
    restart: unless-stopped
    ports:
      - '8080:8080'
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/phonebook_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SERVICE_TAGS: prod
      SERVICE_NAME: phonebook
    depends_on:
      - mysqldb
    networks:
      server:
        aliases:
          - phonebook_api

networks:
  server:
    name: server
    driver: bridge